# Jekyll site
# Package your Jekyll site using the jekyll/builder Docker container image.
# Add steps that build, test, save build artifacts, deploy, and more:
# https://aka.ms/yaml

variables:
  NET_ACCESS_TOKEN: $(netlifyAccessToken)

trigger:
- master

pool: Deadpool

steps:

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'
  
- script: |
    bundle exec jekyll build
  displayName: 'jekyll'

- script:  >-
      zip -r $(Build.ArtifactStagingDirectory)/$(build.BuildId).zip _site/
  displayName: 'Zip Site to $(Build.ArtifactStagingDirectory)/$(build.BuildId).zip'


- script:  >-
      curl
      -H 'Authorization: Bearer $(NET_ACCESS_TOKEN)' 
      -H 'Content-Type: application/zip'
      --data-binary '@$(Build.ArtifactStagingDirectory)/$(build.BuildId).zip'
      https://api.netlify.com/api/v1/sites/$(netlifySiteId)/deploys
  workingDirectory: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Upload to Netlify'